#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_BarNpcDance

#include "Basic.hpp"

#include "AnimBP_BarNpcDance_classes.hpp"
#include "AnimBP_BarNpcDance_parameters.hpp"


namespace SDK
{

// Function AnimBP_BarNpcDance.AnimBP_BarNpcDance_C.ExecuteUbergraph_AnimBP_BarNpcDance
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_BarNpcDance_C::ExecuteUbergraph_AnimBP_BarNpcDance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_BarNpcDance_C", "ExecuteUbergraph_AnimBP_BarNpcDance");

	Params::AnimBP_BarNpcDance_C_ExecuteUbergraph_AnimBP_BarNpcDance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AnimBP_BarNpcDance.AnimBP_BarNpcDance_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UAnimBP_BarNpcDance_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_BarNpcDance_C", "AnimGraph");

	Params::AnimBP_BarNpcDance_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

