#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CannonProjectile

#include "Basic.hpp"

#include "BP_CannonProjectile_classes.hpp"
#include "BP_CannonProjectile_parameters.hpp"


namespace SDK
{

// Function BP_CannonProjectile.BP_CannonProjectile_C.ExecuteUbergraph_BP_CannonProjectile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonProjectile_C::ExecuteUbergraph_BP_CannonProjectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "ExecuteUbergraph_BP_CannonProjectile");

	Params::BP_CannonProjectile_C_ExecuteUbergraph_BP_CannonProjectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.BndEvt__Sphere_K2Node_ComponentBoundEvent_787_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_CannonProjectile_C::BndEvt__Sphere_K2Node_ComponentBoundEvent_787_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "BndEvt__Sphere_K2Node_ComponentBoundEvent_787_ComponentHitSignature__DelegateSignature");

	Params::BP_CannonProjectile_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_787_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CannonProjectile_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.OnSuccess_FE58ED7C433460ED67BE338643AA88A3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonProjectile_C::OnSuccess_FE58ED7C433460ED67BE338643AA88A3(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "OnSuccess_FE58ED7C433460ED67BE338643AA88A3");

	Params::BP_CannonProjectile_C_OnSuccess_FE58ED7C433460ED67BE338643AA88A3 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.OnFailure_FE58ED7C433460ED67BE338643AA88A3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonProjectile_C::OnFailure_FE58ED7C433460ED67BE338643AA88A3(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "OnFailure_FE58ED7C433460ED67BE338643AA88A3");

	Params::BP_CannonProjectile_C_OnFailure_FE58ED7C433460ED67BE338643AA88A3 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.OnSuccess_55094F564F934F663F83948BB1D81B61
// (BlueprintCallable, BlueprintEvent)

void ABP_CannonProjectile_C::OnSuccess_55094F564F934F663F83948BB1D81B61()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "OnSuccess_55094F564F934F663F83948BB1D81B61");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.OnFailure_55094F564F934F663F83948BB1D81B61
// (BlueprintCallable, BlueprintEvent)

void ABP_CannonProjectile_C::OnFailure_55094F564F934F663F83948BB1D81B61()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "OnFailure_55094F564F934F663F83948BB1D81B61");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_CannonProjectile_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CannonProjectile.BP_CannonProjectile_C.ProjectileMatOverride
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInterface*               Material                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonProjectile_C::ProjectileMatOverride(class UMaterialInterface* Material)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonProjectile_C", "ProjectileMatOverride");

	Params::BP_CannonProjectile_C_ProjectileMatOverride Parms{};

	Parms.Material = Material;

	UObject::ProcessEvent(Func, &Parms);
}

}

