#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Castle_FootRest_BP

#include "Basic.hpp"


namespace SDK::Params
{

// Function Castle_FootRest_BP.Castle_FootRest_BP_C.ExecuteUbergraph_Castle_FootRest_BP
// 0x0004 (0x0004 - 0x0000)
struct Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP) == 0x000004, "Wrong alignment on Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP");
static_assert(sizeof(Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP) == 0x000004, "Wrong size on Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP");
static_assert(offsetof(Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP, EntryPoint) == 0x000000, "Member 'Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP::EntryPoint' has a wrong offset!");

}

