#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Castle_FootRest_BP

#include "Basic.hpp"

#include "Castle_FootRest_BP_classes.hpp"
#include "Castle_FootRest_BP_parameters.hpp"


namespace SDK
{

// Function Castle_FootRest_BP.Castle_FootRest_BP_C.ExecuteUbergraph_Castle_FootRest_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACastle_FootRest_BP_C::ExecuteUbergraph_Castle_FootRest_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Castle_FootRest_BP_C", "ExecuteUbergraph_Castle_FootRest_BP");

	Params::Castle_FootRest_BP_C_ExecuteUbergraph_Castle_FootRest_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Castle_FootRest_BP.Castle_FootRest_BP_C.Stop
// (BlueprintCallable, BlueprintEvent)

void ACastle_FootRest_BP_C::Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Castle_FootRest_BP_C", "Stop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Castle_FootRest_BP.Castle_FootRest_BP_C.Active
// (BlueprintCallable, BlueprintEvent)

void ACastle_FootRest_BP_C::Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Castle_FootRest_BP_C", "Active");

	UObject::ProcessEvent(Func, nullptr);
}

}

