#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CastleRoute_TrapTrigger_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function CastleRoute_TrapTrigger_BP.CastleRoute_TrapTrigger_BP_C.ExecuteUbergraph_CastleRoute_TrapTrigger_BP
// 0x0190 (0x0190 - 0x0000)
struct CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_Has_Been_Initd_Variable;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ___bool_IsClosed_Variable;                         // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ___bool_Has_Been_Initd_Variable_1;                 // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0028(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ALTF4_Pawn_SoloPlay_C*              K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play;      // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ALTF4_Chick_Pawn_C*                 K2Node_DynamicCast_AsBP_ALTF4_Chick_Pawn;          // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ALTF4_Pawn_SoloPlay_C*              K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play_1;    // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ALTF4_Chick_Pawn_C*                 K2Node_DynamicCast_AsBP_ALTF4_Chick_Pawn_1;        // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Gameinstance_C>   K2Node_DynamicCast_AsBPI_Gameinstance;             // 0x0120(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_131[0x7];                                      // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USteamMulti_GameInstance_C*             CallFunc_ALTF4GameInstanceRef_ALTF4_GI;            // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_IsClosed_Variable_1;                       // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_ALTF4_Pawn_SoloPlay_C*>      CallFunc_GetAllActorsOfClass_OutActors;            // 0x0148(0x0010)(ReferenceParm)
	TArray<class ABP_ALTF4_Chick_Pawn_C*>         CallFunc_GetAllActorsOfClass_OutActors_1;          // 0x0158(0x0010)(ReferenceParm)
	bool                                          CallFunc_IsOverlappingActor_ReturnValue;           // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsOverlappingActor_ReturnValue_1;         // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_16A[0x6];                                      // 0x016A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetPlayerControllerID_ReturnValue;        // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ALTF4_Pawn_SoloPlay_C*              CallFunc_Array_Get_Item;                           // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_ALTF4_Chick_Pawn_C*                 CallFunc_Array_Get_Item_1;                         // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP) == 0x000008, "Wrong alignment on CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP");
static_assert(sizeof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP) == 0x000190, "Wrong size on CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, EntryPoint) == 0x000000, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, ___bool_Has_Been_Initd_Variable) == 0x000004, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::___bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, ___bool_IsClosed_Variable) == 0x000005, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::___bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, ___bool_Has_Been_Initd_Variable_1) == 0x000006, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::___bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x000008, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000010, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000018, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x000020, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_bFromSweep) == 0x000024, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_SweepResult) == 0x000028, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x0000B8, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OtherActor) == 0x0000C0, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OtherComp) == 0x0000C8, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x0000D0, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play) == 0x0000D8, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_bSuccess) == 0x0000E0, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_AsBP_ALTF4_Chick_Pawn) == 0x0000E8, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_AsBP_ALTF4_Chick_Pawn' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_bSuccess_1) == 0x0000F0, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play_1) == 0x0000F8, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_bSuccess_2) == 0x000100, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_AsBP_ALTF4_Chick_Pawn_1) == 0x000108, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_AsBP_ALTF4_Chick_Pawn_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_bSuccess_3) == 0x000110, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_GetGameInstance_ReturnValue) == 0x000118, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_AsBPI_Gameinstance) == 0x000120, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_AsBPI_Gameinstance' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, K2Node_DynamicCast_bSuccess_4) == 0x000130, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_ALTF4GameInstanceRef_ALTF4_GI) == 0x000138, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_ALTF4GameInstanceRef_ALTF4_GI' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, ___bool_IsClosed_Variable_1) == 0x000140, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::___bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_GetAllActorsOfClass_OutActors) == 0x000148, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_GetAllActorsOfClass_OutActors_1) == 0x000158, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_GetAllActorsOfClass_OutActors_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_IsOverlappingActor_ReturnValue) == 0x000168, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_IsOverlappingActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_IsOverlappingActor_ReturnValue_1) == 0x000169, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_IsOverlappingActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_GetPlayerController_ReturnValue) == 0x000170, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_GetPlayerControllerID_ReturnValue) == 0x000178, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_GetPlayerControllerID_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_Array_Get_Item) == 0x000180, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP, CallFunc_Array_Get_Item_1) == 0x000188, "Member 'CastleRoute_TrapTrigger_BP_C_ExecuteUbergraph_CastleRoute_TrapTrigger_BP::CallFunc_Array_Get_Item_1' has a wrong offset!");

// Function CastleRoute_TrapTrigger_BP.CastleRoute_TrapTrigger_BP_C.BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");
static_assert(sizeof(CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature) == 0x000020, "Wrong size on CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__FishFireTrapTrigger_BP1_Overlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");

// Function CastleRoute_TrapTrigger_BP.CastleRoute_TrapTrigger_BP_C.BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000B0, "Wrong size on CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'CastleRoute_TrapTrigger_BP_C_BndEvt__CannonFireTrigger_BP_Overlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function CastleRoute_TrapTrigger_BP.CastleRoute_TrapTrigger_BP_C.Trap_On
// 0x00F0 (0x00F0 - 0x0000)
struct CastleRoute_TrapTrigger_BP_C_Trap_On final
{
public:
	int32                                         ___int_Variable;                                   // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_1;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_2;                                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_3;                                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_4;                                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_5;                                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AUpDownBalde_Trap_BP_C*>         CallFunc_GetAllActorsOfClassWithTag_OutActors;     // 0x0030(0x0010)(ReferenceParm)
	TArray<class ACastle_FootRest_BP_C*>          CallFunc_GetAllActorsOfClassWithTag_OutActors_1;   // 0x0040(0x0010)(ReferenceParm)
	class AUpDownBalde_Trap_BP_C*                 CallFunc_Array_Get_Item;                           // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACastle_FootRest_BP_C*                  CallFunc_Array_Get_Item_1;                         // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6A[0x6];                                       // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ASplineMover_C*>                 CallFunc_GetAllActorsOfClassWithTag_OutActors_2;   // 0x0070(0x0010)(ReferenceParm)
	TArray<class AJumpJumpTrap_BP_C*>             CallFunc_GetAllActorsOfClassWithTag_OutActors_3;   // 0x0080(0x0010)(ReferenceParm)
	class ASplineMover_C*                         CallFunc_Array_Get_Item_2;                         // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AJumpJumpTrap_BP_C*                     CallFunc_Array_Get_Item_3;                         // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AA[0x6];                                       // 0x00AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ARotationBull_Trap_BP_C*>        CallFunc_GetAllActorsOfClassWithTag_OutActors_4;   // 0x00B0(0x0010)(ReferenceParm)
	TArray<class ASwingSickle_Trap_BP_C*>         CallFunc_GetAllActorsOfClassWithTag_OutActors_5;   // 0x00C0(0x0010)(ReferenceParm)
	class ARotationBull_Trap_BP_C*                CallFunc_Array_Get_Item_4;                         // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASwingSickle_Trap_BP_C*                 CallFunc_Array_Get_Item_5;                         // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x00E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastleRoute_TrapTrigger_BP_C_Trap_On) == 0x000008, "Wrong alignment on CastleRoute_TrapTrigger_BP_C_Trap_On");
static_assert(sizeof(CastleRoute_TrapTrigger_BP_C_Trap_On) == 0x0000F0, "Wrong size on CastleRoute_TrapTrigger_BP_C_Trap_On");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, ___int_Variable) == 0x000000, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::___int_Variable' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, ___int_Variable_1) == 0x000004, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::___int_Variable_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Add_IntInt_ReturnValue_1) == 0x00000C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, ___int_Variable_2) == 0x000010, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::___int_Variable_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, ___int_Variable_3) == 0x000014, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::___int_Variable_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Add_IntInt_ReturnValue_2) == 0x000018, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Add_IntInt_ReturnValue_3) == 0x00001C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, ___int_Variable_4) == 0x000020, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::___int_Variable_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, ___int_Variable_5) == 0x000024, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::___int_Variable_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Add_IntInt_ReturnValue_4) == 0x000028, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Add_IntInt_ReturnValue_5) == 0x00002C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_GetAllActorsOfClassWithTag_OutActors) == 0x000030, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_GetAllActorsOfClassWithTag_OutActors' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_GetAllActorsOfClassWithTag_OutActors_1) == 0x000040, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_GetAllActorsOfClassWithTag_OutActors_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Get_Item) == 0x000050, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Get_Item_1) == 0x000058, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Length_ReturnValue) == 0x000060, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Length_ReturnValue_1) == 0x000064, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Less_IntInt_ReturnValue) == 0x000068, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Less_IntInt_ReturnValue_1) == 0x000069, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_GetAllActorsOfClassWithTag_OutActors_2) == 0x000070, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_GetAllActorsOfClassWithTag_OutActors_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_GetAllActorsOfClassWithTag_OutActors_3) == 0x000080, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_GetAllActorsOfClassWithTag_OutActors_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Get_Item_2) == 0x000090, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Get_Item_3) == 0x000098, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Length_ReturnValue_2) == 0x0000A0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Length_ReturnValue_3) == 0x0000A4, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000A8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Less_IntInt_ReturnValue_3) == 0x0000A9, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_GetAllActorsOfClassWithTag_OutActors_4) == 0x0000B0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_GetAllActorsOfClassWithTag_OutActors_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_GetAllActorsOfClassWithTag_OutActors_5) == 0x0000C0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_GetAllActorsOfClassWithTag_OutActors_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Get_Item_4) == 0x0000D0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Get_Item_5) == 0x0000D8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Length_ReturnValue_4) == 0x0000E0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Array_Length_ReturnValue_5) == 0x0000E4, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Less_IntInt_ReturnValue_4) == 0x0000E8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_On, CallFunc_Less_IntInt_ReturnValue_5) == 0x0000E9, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_On::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");

// Function CastleRoute_TrapTrigger_BP.CastleRoute_TrapTrigger_BP_C.Trap_Off
// 0x01A8 (0x01A8 - 0x0000)
struct CastleRoute_TrapTrigger_BP_C_Trap_Off final
{
public:
	int32                                         ___int_Variable;                                   // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_1;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_2;                                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_3;                                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_4;                                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_5;                                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_6;                                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_7;                                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_7;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_8;                                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_9;                                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_8;                 // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_9;                 // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_10;                                // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_10;                // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AUpDownBalde_Trap_BP_C*>         CallFunc_GetAllActorsOfClassWithTag_OutActors;     // 0x0058(0x0010)(ReferenceParm)
	TArray<class ACastle_FootRest_BP_C*>          CallFunc_GetAllActorsOfClassWithTag_OutActors_1;   // 0x0068(0x0010)(ReferenceParm)
	class AUpDownBalde_Trap_BP_C*                 CallFunc_Array_Get_Item;                           // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACastle_FootRest_BP_C*                  CallFunc_Array_Get_Item_1;                         // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_92[0x6];                                       // 0x0092(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ASplineMover_C*>                 CallFunc_GetAllActorsOfClassWithTag_OutActors_2;   // 0x0098(0x0010)(ReferenceParm)
	TArray<class AJumpJumpTrap_BP_C*>             CallFunc_GetAllActorsOfClassWithTag_OutActors_3;   // 0x00A8(0x0010)(ReferenceParm)
	class ASplineMover_C*                         CallFunc_Array_Get_Item_2;                         // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AJumpJumpTrap_BP_C*                     CallFunc_Array_Get_Item_3;                         // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D2[0x6];                                       // 0x00D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ADrunkNPC_Pawn_C*>               CallFunc_GetAllActorsOfClassWithTag_OutActors_4;   // 0x00D8(0x0010)(ReferenceParm)
	TArray<class ARotationBull_Trap_BP_C*>        CallFunc_GetAllActorsOfClassWithTag_OutActors_5;   // 0x00E8(0x0010)(ReferenceParm)
	class ADrunkNPC_Pawn_C*                       CallFunc_Array_Get_Item_4;                         // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ARotationBull_Trap_BP_C*                CallFunc_Array_Get_Item_5;                         // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_112[0x6];                                      // 0x0112(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AShortCutRouteWall_BP_C*>        CallFunc_GetAllActorsOfClassWithTag_OutActors_6;   // 0x0118(0x0010)(ReferenceParm)
	TArray<class ABarDanceNPC_Pawn_C*>            CallFunc_GetAllActorsOfClassWithTag_OutActors_7;   // 0x0128(0x0010)(ReferenceParm)
	class AShortCutRouteWall_BP_C*                CallFunc_Array_Get_Item_6;                         // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABarDanceNPC_Pawn_C*                    CallFunc_Array_Get_Item_7;                         // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_6;               // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_7;               // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_6;                // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_7;                // 0x0151(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_152[0x6];                                      // 0x0152(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABarNPC_Pawn_C*>                 CallFunc_GetAllActorsOfClassWithTag_OutActors_8;   // 0x0158(0x0010)(ReferenceParm)
	TArray<class ASwingSickle_Trap_BP_C*>         CallFunc_GetAllActorsOfClassWithTag_OutActors_9;   // 0x0168(0x0010)(ReferenceParm)
	class ABarNPC_Pawn_C*                         CallFunc_Array_Get_Item_8;                         // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASwingSickle_Trap_BP_C*                 CallFunc_Array_Get_Item_9;                         // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_8;               // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_9;               // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_8;                // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_9;                // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_192[0x6];                                      // 0x0192(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABarNPC_Pawn_C*                         CallFunc_Array_Get_Item_10;                        // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_10;              // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_10;               // 0x01A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CastleRoute_TrapTrigger_BP_C_Trap_Off) == 0x000008, "Wrong alignment on CastleRoute_TrapTrigger_BP_C_Trap_Off");
static_assert(sizeof(CastleRoute_TrapTrigger_BP_C_Trap_Off) == 0x0001A8, "Wrong size on CastleRoute_TrapTrigger_BP_C_Trap_Off");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable) == 0x000000, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_1) == 0x000004, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_1) == 0x00000C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_2) == 0x000010, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_3) == 0x000014, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_2) == 0x000018, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_3) == 0x00001C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_4) == 0x000020, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_5) == 0x000024, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_4) == 0x000028, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_5) == 0x00002C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_6) == 0x000030, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_6' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_7) == 0x000034, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_7' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_6) == 0x000038, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_7) == 0x00003C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_8) == 0x000040, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_8' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_9) == 0x000044, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_9' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_8) == 0x000048, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_9) == 0x00004C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, ___int_Variable_10) == 0x000050, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::___int_Variable_10' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Add_IntInt_ReturnValue_10) == 0x000054, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Add_IntInt_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors) == 0x000058, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_1) == 0x000068, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item) == 0x000078, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_1) == 0x000080, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue) == 0x000088, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_1) == 0x00008C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue) == 0x000090, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_1) == 0x000091, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_2) == 0x000098, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_3) == 0x0000A8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_2) == 0x0000B8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_3) == 0x0000C0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_2) == 0x0000C8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_3) == 0x0000CC, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000D0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_3) == 0x0000D1, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_4) == 0x0000D8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_5) == 0x0000E8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_4) == 0x0000F8, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_5) == 0x000100, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_4) == 0x000108, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_5) == 0x00010C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_4) == 0x000110, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_5) == 0x000111, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_6) == 0x000118, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_6' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_7) == 0x000128, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_7' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_6) == 0x000138, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_7) == 0x000140, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_7' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_6) == 0x000148, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_7) == 0x00014C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_6) == 0x000150, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_7) == 0x000151, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_8) == 0x000158, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_8' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_GetAllActorsOfClassWithTag_OutActors_9) == 0x000168, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_GetAllActorsOfClassWithTag_OutActors_9' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_8) == 0x000178, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_8' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_9) == 0x000180, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_9' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_8) == 0x000188, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_9) == 0x00018C, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_8) == 0x000190, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_9) == 0x000191, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Get_Item_10) == 0x000198, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Get_Item_10' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Array_Length_ReturnValue_10) == 0x0001A0, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Array_Length_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(CastleRoute_TrapTrigger_BP_C_Trap_Off, CallFunc_Less_IntInt_ReturnValue_10) == 0x0001A4, "Member 'CastleRoute_TrapTrigger_BP_C_Trap_Off::CallFunc_Less_IntInt_ReturnValue_10' has a wrong offset!");

}

