#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CheeringNPC_Trap_BP

#include "Basic.hpp"

#include "CheeringNPC_Trap_BP_classes.hpp"
#include "CheeringNPC_Trap_BP_parameters.hpp"


namespace SDK
{

// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.ExecuteUbergraph_CheeringNPC_Trap_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACheeringNPC_Trap_BP_C::ExecuteUbergraph_CheeringNPC_Trap_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "ExecuteUbergraph_CheeringNPC_Trap_BP");

	Params::CheeringNPC_Trap_BP_C_ExecuteUbergraph_CheeringNPC_Trap_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.Reset
// (BlueprintCallable, BlueprintEvent)

void ACheeringNPC_Trap_BP_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.BndEvt__CheeringNPC_Trap_BP_L_Weapon_03_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ACheeringNPC_Trap_BP_C::BndEvt__CheeringNPC_Trap_BP_L_Weapon_03_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "BndEvt__CheeringNPC_Trap_BP_L_Weapon_03_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature");

	Params::CheeringNPC_Trap_BP_C_BndEvt__CheeringNPC_Trap_BP_L_Weapon_03_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.BndEvt__CheeringNPC_Trap_BP_R_Weapon_03_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ACheeringNPC_Trap_BP_C::BndEvt__CheeringNPC_Trap_BP_R_Weapon_03_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "BndEvt__CheeringNPC_Trap_BP_R_Weapon_03_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature");

	Params::CheeringNPC_Trap_BP_C_BndEvt__CheeringNPC_Trap_BP_R_Weapon_03_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.BndEvt__CheeringNPC_Trap_BP_L_Dead_Zone_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ACheeringNPC_Trap_BP_C::BndEvt__CheeringNPC_Trap_BP_L_Dead_Zone_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "BndEvt__CheeringNPC_Trap_BP_L_Dead_Zone_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");

	Params::CheeringNPC_Trap_BP_C_BndEvt__CheeringNPC_Trap_BP_L_Dead_Zone_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.BndEvt__CheeringNPC_Trap_BP_R_Dead_Zone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ACheeringNPC_Trap_BP_C::BndEvt__CheeringNPC_Trap_BP_R_Dead_Zone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "BndEvt__CheeringNPC_Trap_BP_R_Dead_Zone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::CheeringNPC_Trap_BP_C_BndEvt__CheeringNPC_Trap_BP_R_Dead_Zone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.StopNPC
// (BlueprintCallable, BlueprintEvent)

void ACheeringNPC_Trap_BP_C::StopNPC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "StopNPC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.Open
// (BlueprintCallable, BlueprintEvent)

void ACheeringNPC_Trap_BP_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.ActiveNPC
// (BlueprintCallable, BlueprintEvent)

void ACheeringNPC_Trap_BP_C::ActiveNPC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "ActiveNPC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.Rota__ResetEvent__EventFunc
// (BlueprintEvent)

void ACheeringNPC_Trap_BP_C::Rota__ResetEvent__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "Rota__ResetEvent__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.Rota__SoundEvent__EventFunc
// (BlueprintEvent)

void ACheeringNPC_Trap_BP_C::Rota__SoundEvent__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "Rota__SoundEvent__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.Rota__UpdateFunc
// (BlueprintEvent)

void ACheeringNPC_Trap_BP_C::Rota__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "Rota__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.Rota__FinishedFunc
// (BlueprintEvent)

void ACheeringNPC_Trap_BP_C::Rota__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "Rota__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CheeringNPC_Trap_BP.CheeringNPC_Trap_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACheeringNPC_Trap_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CheeringNPC_Trap_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

