#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreditsWidgetBP

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function CreditsWidgetBP.CreditsWidgetBP_C.ExecuteUbergraph_CreditsWidgetBP
// 0x00B0 (0x00B0 - 0x0000)
struct CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UInteractableMenuWidgetBP_C*            K2Node_Event_NavigateToMenu;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInteractableMenuWidgetBP_C*            K2Node_Event_NavigateFromMenu_1;                   // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOptionsOverviewWidgetBP_C*             K2Node_DynamicCast_AsOptions_Overview_Widget_BP;   // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UInteractableMenuWidgetBP_C*            K2Node_Event_NavigateFromMenu;                     // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsGamepadBeingUsed;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenuContainerWidgetBP_C*           K2Node_DynamicCast_AsMain_Menu_Container_Widget_BP; // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UOptionsOverviewWidgetBP_C*             K2Node_DynamicCast_AsOptions_Overview_Widget_BP_1; // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenuContainerWidgetBP_C*           K2Node_DynamicCast_AsMain_Menu_Container_Widget_BP_1; // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_GetGlobalSounds_SelectSound;              // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_GetGlobalSounds_BackSound;                // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_GetGlobalSounds_HoverSound;               // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_GetGlobalSounds_ChangeSound;              // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_GetGlobalSounds_SliderSound;              // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_GetGlobalSounds_BackgroundMusic;          // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundCue*                              CallFunc_GetGlobalSounds_CreditsMusic;             // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSound2D_ReturnValue;                 // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP) == 0x000008, "Wrong alignment on CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP");
static_assert(sizeof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP) == 0x0000B0, "Wrong size on CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, EntryPoint) == 0x000000, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_Event_NavigateToMenu) == 0x000008, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_Event_NavigateToMenu' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_Event_NavigateFromMenu_1) == 0x000010, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_Event_NavigateFromMenu_1' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_AsOptions_Overview_Widget_BP) == 0x000018, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_AsOptions_Overview_Widget_BP' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_Event_NavigateFromMenu) == 0x000028, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_Event_NavigateFromMenu' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_Event_bIsGamepadBeingUsed) == 0x000030, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_Event_bIsGamepadBeingUsed' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_AsMain_Menu_Container_Widget_BP) == 0x000038, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_AsMain_Menu_Container_Widget_BP' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_bSuccess_1) == 0x000040, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_AsOptions_Overview_Widget_BP_1) == 0x000048, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_AsOptions_Overview_Widget_BP_1' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_bSuccess_2) == 0x000050, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_AsMain_Menu_Container_Widget_BP_1) == 0x000058, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_AsMain_Menu_Container_Widget_BP_1' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, K2Node_DynamicCast_bSuccess_3) == 0x000060, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_PlayAnimation_ReturnValue) == 0x000068, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_GetGlobalSounds_SelectSound) == 0x000070, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_GetGlobalSounds_SelectSound' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_GetGlobalSounds_BackSound) == 0x000078, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_GetGlobalSounds_BackSound' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_GetGlobalSounds_HoverSound) == 0x000080, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_GetGlobalSounds_HoverSound' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_GetGlobalSounds_ChangeSound) == 0x000088, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_GetGlobalSounds_ChangeSound' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_GetGlobalSounds_SliderSound) == 0x000090, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_GetGlobalSounds_SliderSound' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_GetGlobalSounds_BackgroundMusic) == 0x000098, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_GetGlobalSounds_BackgroundMusic' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_GetGlobalSounds_CreditsMusic) == 0x0000A0, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_GetGlobalSounds_CreditsMusic' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP, CallFunc_SpawnSound2D_ReturnValue) == 0x0000A8, "Member 'CreditsWidgetBP_C_ExecuteUbergraph_CreditsWidgetBP::CallFunc_SpawnSound2D_ReturnValue' has a wrong offset!");

// Function CreditsWidgetBP.CreditsWidgetBP_C.SetGlobalSettings
// 0x0250 (0x0250 - 0x0000)
struct CreditsWidgetBP_C_SetGlobalSettings final
{
public:
	struct FSlateFontInfo                         CallFunc_GetGlobalFonts_MainFont;                  // 0x0000(0x0058)(HasGetValueTypeHash)
	struct FSlateFontInfo                         CallFunc_GetGlobalFonts_SmallTitleFont;            // 0x0058(0x0058)(HasGetValueTypeHash)
	struct FSlateFontInfo                         CallFunc_GetGlobalFonts_MediumTitleFont;           // 0x00B0(0x0058)(HasGetValueTypeHash)
	struct FSlateFontInfo                         CallFunc_GetGlobalFonts_LargeTitleFont;            // 0x0108(0x0058)(HasGetValueTypeHash)
	struct FSlateFontInfo                         CallFunc_GetGlobalFonts_ValueFont;                 // 0x0160(0x0058)(HasGetValueTypeHash)
	bool                                          CallFunc_GetGlobalFonts_OnlyUppercase;             // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x3];                                      // 0x01B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetGlobalColors_MainColor;                // 0x01BC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_HighlightColor;           // 0x01CC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_HighlightExtraColor;      // 0x01DC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_MenuBackgroundColor;      // 0x01EC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_WidgetBackgroundColor;    // 0x01FC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_SymbolColor;              // 0x020C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_SubtleColor;              // 0x021C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_DecisionButtonColor;      // 0x022C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetGlobalColors_SliderBackgroundColor;    // 0x023C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreditsWidgetBP_C_SetGlobalSettings) == 0x000008, "Wrong alignment on CreditsWidgetBP_C_SetGlobalSettings");
static_assert(sizeof(CreditsWidgetBP_C_SetGlobalSettings) == 0x000250, "Wrong size on CreditsWidgetBP_C_SetGlobalSettings");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalFonts_MainFont) == 0x000000, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalFonts_MainFont' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalFonts_SmallTitleFont) == 0x000058, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalFonts_SmallTitleFont' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalFonts_MediumTitleFont) == 0x0000B0, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalFonts_MediumTitleFont' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalFonts_LargeTitleFont) == 0x000108, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalFonts_LargeTitleFont' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalFonts_ValueFont) == 0x000160, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalFonts_ValueFont' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalFonts_OnlyUppercase) == 0x0001B8, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalFonts_OnlyUppercase' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_MainColor) == 0x0001BC, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_MainColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_HighlightColor) == 0x0001CC, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_HighlightColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_HighlightExtraColor) == 0x0001DC, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_HighlightExtraColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_MenuBackgroundColor) == 0x0001EC, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_MenuBackgroundColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_WidgetBackgroundColor) == 0x0001FC, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_WidgetBackgroundColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_SymbolColor) == 0x00020C, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_SymbolColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_SubtleColor) == 0x00021C, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_SubtleColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_DecisionButtonColor) == 0x00022C, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_DecisionButtonColor' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_SetGlobalSettings, CallFunc_GetGlobalColors_SliderBackgroundColor) == 0x00023C, "Member 'CreditsWidgetBP_C_SetGlobalSettings::CallFunc_GetGlobalColors_SliderBackgroundColor' has a wrong offset!");

// Function CreditsWidgetBP.CreditsWidgetBP_C.OnNavigationEnter
// 0x0010 (0x0010 - 0x0000)
struct CreditsWidgetBP_C_OnNavigationEnter final
{
public:
	class UInteractableMenuWidgetBP_C*            NavigateFromMenu;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Param_bIsGamepadBeingUsed;                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CreditsWidgetBP_C_OnNavigationEnter) == 0x000008, "Wrong alignment on CreditsWidgetBP_C_OnNavigationEnter");
static_assert(sizeof(CreditsWidgetBP_C_OnNavigationEnter) == 0x000010, "Wrong size on CreditsWidgetBP_C_OnNavigationEnter");
static_assert(offsetof(CreditsWidgetBP_C_OnNavigationEnter, NavigateFromMenu) == 0x000000, "Member 'CreditsWidgetBP_C_OnNavigationEnter::NavigateFromMenu' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_OnNavigationEnter, Param_bIsGamepadBeingUsed) == 0x000008, "Member 'CreditsWidgetBP_C_OnNavigationEnter::Param_bIsGamepadBeingUsed' has a wrong offset!");

// Function CreditsWidgetBP.CreditsWidgetBP_C.OnNavigationExit
// 0x0010 (0x0010 - 0x0000)
struct CreditsWidgetBP_C_OnNavigationExit final
{
public:
	class UInteractableMenuWidgetBP_C*            NavigateToMenu;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInteractableMenuWidgetBP_C*            NavigateFromMenu;                                  // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CreditsWidgetBP_C_OnNavigationExit) == 0x000008, "Wrong alignment on CreditsWidgetBP_C_OnNavigationExit");
static_assert(sizeof(CreditsWidgetBP_C_OnNavigationExit) == 0x000010, "Wrong size on CreditsWidgetBP_C_OnNavigationExit");
static_assert(offsetof(CreditsWidgetBP_C_OnNavigationExit, NavigateToMenu) == 0x000000, "Member 'CreditsWidgetBP_C_OnNavigationExit::NavigateToMenu' has a wrong offset!");
static_assert(offsetof(CreditsWidgetBP_C_OnNavigationExit, NavigateFromMenu) == 0x000008, "Member 'CreditsWidgetBP_C_OnNavigationExit::NavigateFromMenu' has a wrong offset!");

}

