#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dead_NormalBody_BP

#include "Basic.hpp"


namespace SDK::Params
{

// Function Dead_NormalBody_BP.Dead_NormalBody_BP_C.UserConstructionScript
// 0x0030 (0x0030 - 0x0000)
struct Dead_NormalBody_BP_C_UserConstructionScript final
{
public:
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Gameinstance_C>   K2Node_DynamicCast_AsBPI_Gameinstance;             // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USteamMulti_GameInstance_C*             CallFunc_ALTF4GameInstanceRef_ALTF4_GI;            // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_2;          // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_3;          // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Dead_NormalBody_BP_C_UserConstructionScript) == 0x000008, "Wrong alignment on Dead_NormalBody_BP_C_UserConstructionScript");
static_assert(sizeof(Dead_NormalBody_BP_C_UserConstructionScript) == 0x000030, "Wrong size on Dead_NormalBody_BP_C_UserConstructionScript");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, CallFunc_GetGameInstance_ReturnValue) == 0x000000, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, K2Node_DynamicCast_AsBPI_Gameinstance) == 0x000008, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::K2Node_DynamicCast_AsBPI_Gameinstance' has a wrong offset!");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, CallFunc_ALTF4GameInstanceRef_ALTF4_GI) == 0x000020, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::CallFunc_ALTF4GameInstanceRef_ALTF4_GI' has a wrong offset!");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000028, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, CallFunc_EqualEqual_IntInt_ReturnValue_1) == 0x000029, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::CallFunc_EqualEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, CallFunc_EqualEqual_IntInt_ReturnValue_2) == 0x00002A, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::CallFunc_EqualEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Dead_NormalBody_BP_C_UserConstructionScript, CallFunc_EqualEqual_IntInt_ReturnValue_3) == 0x00002B, "Member 'Dead_NormalBody_BP_C_UserConstructionScript::CallFunc_EqualEqual_IntInt_ReturnValue_3' has a wrong offset!");

}

