#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ElevatorTrap_BP

#include "Basic.hpp"

#include "ElevatorTrap_BP_classes.hpp"
#include "ElevatorTrap_BP_parameters.hpp"


namespace SDK
{

// Function ElevatorTrap_BP.ElevatorTrap_BP_C.ExecuteUbergraph_ElevatorTrap_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AElevatorTrap_BP_C::ExecuteUbergraph_ElevatorTrap_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "ExecuteUbergraph_ElevatorTrap_BP");

	Params::ElevatorTrap_BP_C_ExecuteUbergraph_ElevatorTrap_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.Stop
// (BlueprintCallable, BlueprintEvent)

void AElevatorTrap_BP_C::Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "Stop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.PoleRota_Stop
// (BlueprintCallable, BlueprintEvent)

void AElevatorTrap_BP_C::PoleRota_Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "PoleRota_Stop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.BndEvt__ElevatorTrap_BP_DeathZone_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AElevatorTrap_BP_C::BndEvt__ElevatorTrap_BP_DeathZone_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "BndEvt__ElevatorTrap_BP_DeathZone_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");

	Params::ElevatorTrap_BP_C_BndEvt__ElevatorTrap_BP_DeathZone_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AElevatorTrap_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.Active
// (BlueprintCallable, BlueprintEvent)

void AElevatorTrap_BP_C::Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.PoleRota_Down
// (BlueprintCallable, BlueprintEvent)

void AElevatorTrap_BP_C::PoleRota_Down()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "PoleRota_Down");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.PoleRota_Up
// (BlueprintCallable, BlueprintEvent)

void AElevatorTrap_BP_C::PoleRota_Up()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "PoleRota_Up");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.UpDown__UpRotationEvent__EventFunc
// (BlueprintEvent)

void AElevatorTrap_BP_C::UpDown__UpRotationEvent__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "UpDown__UpRotationEvent__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.UpDown__DownRotationEvent__EventFunc
// (BlueprintEvent)

void AElevatorTrap_BP_C::UpDown__DownRotationEvent__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "UpDown__DownRotationEvent__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.UpDown__StopRotationEvent__EventFunc
// (BlueprintEvent)

void AElevatorTrap_BP_C::UpDown__StopRotationEvent__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "UpDown__StopRotationEvent__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.UpDown__UpdateFunc
// (BlueprintEvent)

void AElevatorTrap_BP_C::UpDown__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "UpDown__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.UpDown__FinishedFunc
// (BlueprintEvent)

void AElevatorTrap_BP_C::UpDown__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "UpDown__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ElevatorTrap_BP.ElevatorTrap_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AElevatorTrap_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ElevatorTrap_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

