#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EpicLeaderboardEntryInterface

#include "Basic.hpp"

#include "EpicLeaderboardEntryInterface_classes.hpp"
#include "EpicLeaderboardEntryInterface_parameters.hpp"


namespace SDK
{

// Function EpicLeaderboardEntryInterface.EpicLeaderboardEntryInterface_C.InitFields
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Highlight                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FEpicLeaderboardEntry            ScoreEntry                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void IEpicLeaderboardEntryInterface_C::InitFields(bool Highlight, const struct FEpicLeaderboardEntry& ScoreEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EpicLeaderboardEntryInterface_C", "InitFields");

	Params::EpicLeaderboardEntryInterface_C_InitFields Parms{};

	Parms.Highlight = Highlight;
	Parms.ScoreEntry = std::move(ScoreEntry);

	UObject::ProcessEvent(Func, &Parms);
}

}

