#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EpicLeaderboardFrame

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass EpicLeaderboardFrame.EpicLeaderboardFrame_C
// 0x0070 (0x02D0 - 0x0260)
class UEpicLeaderboardFrame_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOutLoadingAnimation;                           // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LoadingAnimation;                                  // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Loading;                                           // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScoresContainer;                                   // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_2;                                       // 0x0288(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VbBoard;                                           // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUserWidget*                            HighlightedScore;                                  // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            SpotlightEntryWidget;                              // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USteamMulti_GameInstance_C*             ALTF4_GI;                                          // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 ScoreString;                                       // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          Challenge_;                                        // 0x02C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C1[0x7];                                      // 0x02C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 EntryClass;                                        // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_EpicLeaderboardFrame(int32 EntryPoint);
	void Construct();
	void UpdateScores(TArray<struct FEpicLeaderboardEntry>& Leaderboard_Entries, const struct FEpicLeaderboardEntry& SpotlightEntry, const class FString& HighlightUser, class UClass* EntryClass_0);
	void StartLoadingAnimation();
	void StopLoadingAnimation();
	class FText Score_ModeCheck();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EpicLeaderboardFrame_C">();
	}
	static class UEpicLeaderboardFrame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEpicLeaderboardFrame_C>();
	}
};
static_assert(alignof(UEpicLeaderboardFrame_C) == 0x000008, "Wrong alignment on UEpicLeaderboardFrame_C");
static_assert(sizeof(UEpicLeaderboardFrame_C) == 0x0002D0, "Wrong size on UEpicLeaderboardFrame_C");
static_assert(offsetof(UEpicLeaderboardFrame_C, UberGraphFrame) == 0x000260, "Member 'UEpicLeaderboardFrame_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, FadeOutLoadingAnimation) == 0x000268, "Member 'UEpicLeaderboardFrame_C::FadeOutLoadingAnimation' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, LoadingAnimation) == 0x000270, "Member 'UEpicLeaderboardFrame_C::LoadingAnimation' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, Loading) == 0x000278, "Member 'UEpicLeaderboardFrame_C::Loading' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, ScoresContainer) == 0x000280, "Member 'UEpicLeaderboardFrame_C::ScoresContainer' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, TextBlock_2) == 0x000288, "Member 'UEpicLeaderboardFrame_C::TextBlock_2' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, VbBoard) == 0x000290, "Member 'UEpicLeaderboardFrame_C::VbBoard' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, HighlightedScore) == 0x000298, "Member 'UEpicLeaderboardFrame_C::HighlightedScore' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, SpotlightEntryWidget) == 0x0002A0, "Member 'UEpicLeaderboardFrame_C::SpotlightEntryWidget' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, ALTF4_GI) == 0x0002A8, "Member 'UEpicLeaderboardFrame_C::ALTF4_GI' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, ScoreString) == 0x0002B0, "Member 'UEpicLeaderboardFrame_C::ScoreString' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, Challenge_) == 0x0002C0, "Member 'UEpicLeaderboardFrame_C::Challenge_' has a wrong offset!");
static_assert(offsetof(UEpicLeaderboardFrame_C, EntryClass) == 0x0002C8, "Member 'UEpicLeaderboardFrame_C::EntryClass' has a wrong offset!");

}

