#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EpicLeaderboardFrame

#include "Basic.hpp"

#include "EpicLeaderboard_structs.hpp"


namespace SDK::Params
{

// Function EpicLeaderboardFrame.EpicLeaderboardFrame_C.ExecuteUbergraph_EpicLeaderboardFrame
// 0x0030 (0x0030 - 0x0000)
struct EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Gameinstance_C>   K2Node_DynamicCast_AsBPI_Gameinstance;             // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USteamMulti_GameInstance_C*             CallFunc_ALTF4GameInstanceRef_ALTF4_GI;            // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame) == 0x000008, "Wrong alignment on EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame");
static_assert(sizeof(EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame) == 0x000030, "Wrong size on EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame");
static_assert(offsetof(EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame, EntryPoint) == 0x000000, "Member 'EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame::EntryPoint' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame, CallFunc_GetGameInstance_ReturnValue) == 0x000008, "Member 'EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame, K2Node_DynamicCast_AsBPI_Gameinstance) == 0x000010, "Member 'EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame::K2Node_DynamicCast_AsBPI_Gameinstance' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame, CallFunc_ALTF4GameInstanceRef_ALTF4_GI) == 0x000028, "Member 'EpicLeaderboardFrame_C_ExecuteUbergraph_EpicLeaderboardFrame::CallFunc_ALTF4GameInstanceRef_ALTF4_GI' has a wrong offset!");

// Function EpicLeaderboardFrame.EpicLeaderboardFrame_C.UpdateScores
// 0x02C8 (0x02C8 - 0x0000)
struct EpicLeaderboardFrame_C_UpdateScores final
{
public:
	TArray<struct FEpicLeaderboardEntry>          Leaderboard_Entries;                               // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEpicLeaderboardEntry                  SpotlightEntry;                                    // 0x0010(0x0098)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FString                                 HighlightUser;                                     // 0x00A8(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UClass*                                 EntryClass_0;                                      // 0x00B8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UChallenge_EpicLeaderboardEntry_C*      CallFunc_Create_ReturnValue;                       // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IEpicLeaderboardEntryInterface_C> K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface; // 0x00D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IEpicLeaderboardEntryInterface_C> K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_1; // 0x00E8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_RemoveChild_ReturnValue;                  // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FB[0x1];                                       // 0x00FB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Array_Index_Variable;                       // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x3];                                      // 0x0101(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Array_Index_Variable_1;                     // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_Create_ReturnValue_1;                     // 0x0108(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEpicLeaderboardEntry                  CallFunc_Array_Get_Item;                           // 0x0110(0x0098)()
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x01A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1AA[0x2];                                      // 0x01AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_1;                   // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_Create_ReturnValue_2;                     // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_2;                   // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RemoveChild_ReturnValue_1;                // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1CA[0x2];                                      // 0x01CA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Loop_Counter_Variable;                      // 0x01CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x3];                                      // 0x01D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IEpicLeaderboardEntryInterface_C> K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_2; // 0x01D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEpicLeaderboardEntry                  CallFunc_Array_Get_Item_1;                         // 0x01F0(0x0098)()
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_1;          // 0x028C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x028D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_28E[0x2];                                      // 0x028E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UItem_EpicLeaderboardEntry_C*           CallFunc_Create_ReturnValue_3;                     // 0x0290(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IEpicLeaderboardEntryInterface_C> K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_3; // 0x02A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x3];                                      // 0x02B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Loop_Counter_Variable_1;                    // 0x02B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B9[0x3];                                      // 0x02B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x02BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_3;                   // 0x02C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(EpicLeaderboardFrame_C_UpdateScores) == 0x000008, "Wrong alignment on EpicLeaderboardFrame_C_UpdateScores");
static_assert(sizeof(EpicLeaderboardFrame_C_UpdateScores) == 0x0002C8, "Wrong size on EpicLeaderboardFrame_C_UpdateScores");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, Leaderboard_Entries) == 0x000000, "Member 'EpicLeaderboardFrame_C_UpdateScores::Leaderboard_Entries' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, SpotlightEntry) == 0x000010, "Member 'EpicLeaderboardFrame_C_UpdateScores::SpotlightEntry' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, HighlightUser) == 0x0000A8, "Member 'EpicLeaderboardFrame_C_UpdateScores::HighlightUser' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, EntryClass_0) == 0x0000B8, "Member 'EpicLeaderboardFrame_C_UpdateScores::EntryClass_0' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_AddChild_ReturnValue) == 0x0000C0, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Create_ReturnValue) == 0x0000C8, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface) == 0x0000D0, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_bSuccess) == 0x0000E0, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_1) == 0x0000E8, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_bSuccess_1) == 0x0000F8, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_RemoveChild_ReturnValue) == 0x0000F9, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_RemoveChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_IsValid_ReturnValue) == 0x0000FA, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, ___int_Array_Index_Variable) == 0x0000FC, "Member 'EpicLeaderboardFrame_C_UpdateScores::___int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000100, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, ___int_Array_Index_Variable_1) == 0x000104, "Member 'EpicLeaderboardFrame_C_UpdateScores::___int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Create_ReturnValue_1) == 0x000108, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Array_Get_Item) == 0x000110, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_IsValid_ReturnValue_1) == 0x0001A8, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x0001A9, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Array_Length_ReturnValue) == 0x0001AC, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_AddChild_ReturnValue_1) == 0x0001B0, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_AddChild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Create_ReturnValue_2) == 0x0001B8, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_AddChild_ReturnValue_2) == 0x0001C0, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_AddChild_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_RemoveChild_ReturnValue_1) == 0x0001C8, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_RemoveChild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_IsValid_ReturnValue_2) == 0x0001C9, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, ___int_Loop_Counter_Variable) == 0x0001CC, "Member 'EpicLeaderboardFrame_C_UpdateScores::___int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_EqualEqual_IntInt_ReturnValue_1) == 0x0001D0, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_EqualEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Add_IntInt_ReturnValue) == 0x0001D4, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_2) == 0x0001D8, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_2' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_bSuccess_2) == 0x0001E8, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Array_Get_Item_1) == 0x0001F0, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Array_Length_ReturnValue_1) == 0x000288, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_EqualEqual_StrStr_ReturnValue_1) == 0x00028C, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_EqualEqual_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Less_IntInt_ReturnValue) == 0x00028D, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Create_ReturnValue_3) == 0x000290, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Create_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_IsValid_ReturnValue_3) == 0x000298, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_3) == 0x0002A0, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_AsEpic_Leaderboard_Entry_Interface_3' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, K2Node_DynamicCast_bSuccess_3) == 0x0002B0, "Member 'EpicLeaderboardFrame_C_UpdateScores::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, ___int_Loop_Counter_Variable_1) == 0x0002B4, "Member 'EpicLeaderboardFrame_C_UpdateScores::___int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Less_IntInt_ReturnValue_1) == 0x0002B8, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_Add_IntInt_ReturnValue_1) == 0x0002BC, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_UpdateScores, CallFunc_AddChild_ReturnValue_3) == 0x0002C0, "Member 'EpicLeaderboardFrame_C_UpdateScores::CallFunc_AddChild_ReturnValue_3' has a wrong offset!");

// Function EpicLeaderboardFrame.EpicLeaderboardFrame_C.StartLoadingAnimation
// 0x0008 (0x0008 - 0x0000)
struct EpicLeaderboardFrame_C_StartLoadingAnimation final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(EpicLeaderboardFrame_C_StartLoadingAnimation) == 0x000008, "Wrong alignment on EpicLeaderboardFrame_C_StartLoadingAnimation");
static_assert(sizeof(EpicLeaderboardFrame_C_StartLoadingAnimation) == 0x000008, "Wrong size on EpicLeaderboardFrame_C_StartLoadingAnimation");
static_assert(offsetof(EpicLeaderboardFrame_C_StartLoadingAnimation, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'EpicLeaderboardFrame_C_StartLoadingAnimation::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function EpicLeaderboardFrame.EpicLeaderboardFrame_C.StopLoadingAnimation
// 0x0008 (0x0008 - 0x0000)
struct EpicLeaderboardFrame_C_StopLoadingAnimation final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(EpicLeaderboardFrame_C_StopLoadingAnimation) == 0x000008, "Wrong alignment on EpicLeaderboardFrame_C_StopLoadingAnimation");
static_assert(sizeof(EpicLeaderboardFrame_C_StopLoadingAnimation) == 0x000008, "Wrong size on EpicLeaderboardFrame_C_StopLoadingAnimation");
static_assert(offsetof(EpicLeaderboardFrame_C_StopLoadingAnimation, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'EpicLeaderboardFrame_C_StopLoadingAnimation::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function EpicLeaderboardFrame.EpicLeaderboardFrame_C.Score_ModeCheck
// 0x0030 (0x0030 - 0x0000)
struct EpicLeaderboardFrame_C_Score_ModeCheck final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0018)()
};
static_assert(alignof(EpicLeaderboardFrame_C_Score_ModeCheck) == 0x000008, "Wrong alignment on EpicLeaderboardFrame_C_Score_ModeCheck");
static_assert(sizeof(EpicLeaderboardFrame_C_Score_ModeCheck) == 0x000030, "Wrong size on EpicLeaderboardFrame_C_Score_ModeCheck");
static_assert(offsetof(EpicLeaderboardFrame_C_Score_ModeCheck, ReturnValue) == 0x000000, "Member 'EpicLeaderboardFrame_C_Score_ModeCheck::ReturnValue' has a wrong offset!");
static_assert(offsetof(EpicLeaderboardFrame_C_Score_ModeCheck, CallFunc_Conv_StringToText_ReturnValue) == 0x000018, "Member 'EpicLeaderboardFrame_C_Score_ModeCheck::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

}

