#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Goose_shot

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function goose_shot.goose_shot_C.ExecuteUbergraph_goose_shot
// 0x01B0 (0x01B0 - 0x0000)
struct Goose_shot_C_ExecuteUbergraph_goose_shot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0028(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Pawn_C*                             K2Node_DynamicCast_AsBP_Pawn;                      // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AStaticMeshActor*                       K2Node_CustomEvent_set_target;                     // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CallFunc_K2_GetRootComponent_ReturnValue;          // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x00E8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_HitComponent;           // 0x0100(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0110(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_NormalImpulse;          // 0x0118(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_ComponentBoundEvent_Hit;                    // 0x0124(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Goose_shot_C_ExecuteUbergraph_goose_shot) == 0x000008, "Wrong alignment on Goose_shot_C_ExecuteUbergraph_goose_shot");
static_assert(sizeof(Goose_shot_C_ExecuteUbergraph_goose_shot) == 0x0001B0, "Wrong size on Goose_shot_C_ExecuteUbergraph_goose_shot");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, EntryPoint) == 0x000000, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::EntryPoint' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000008, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_OtherActor) == 0x000010, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_OtherComp) == 0x000018, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000020, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_bFromSweep) == 0x000024, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_SweepResult) == 0x000028, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_DynamicCast_AsBP_Pawn) == 0x0000B8, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_DynamicCast_AsBP_Pawn' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_DynamicCast_bSuccess) == 0x0000C0, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_CustomEvent_set_target) == 0x0000C8, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_CustomEvent_set_target' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, CallFunc_K2_GetRootComponent_ReturnValue) == 0x0000D0, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::CallFunc_K2_GetRootComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, CallFunc_GetDisplayName_ReturnValue) == 0x0000D8, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0000E8, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x0000F8, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_HitComponent) == 0x000100, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_HitComponent' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000108, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000110, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_NormalImpulse) == 0x000118, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_NormalImpulse' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_ExecuteUbergraph_goose_shot, K2Node_ComponentBoundEvent_Hit) == 0x000124, "Member 'Goose_shot_C_ExecuteUbergraph_goose_shot::K2Node_ComponentBoundEvent_Hit' has a wrong offset!");

// Function goose_shot.goose_shot_C.BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000B0, "Wrong size on Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Goose_shot_C_BndEvt__SkeletalMesh1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function goose_shot.goose_shot_C.BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0024(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature) == 0x000008, "Wrong alignment on Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature");
static_assert(sizeof(Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature) == 0x0000B0, "Wrong size on Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature");
static_assert(offsetof(Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature, HitComponent) == 0x000000, "Member 'Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature::HitComponent' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature, NormalImpulse) == 0x000018, "Member 'Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature::NormalImpulse' has a wrong offset!");
static_assert(offsetof(Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature, Hit) == 0x000024, "Member 'Goose_shot_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature::Hit' has a wrong offset!");

// Function goose_shot.goose_shot_C.homing
// 0x0008 (0x0008 - 0x0000)
struct Goose_shot_C_Homing final
{
public:
	class AStaticMeshActor*                       Set_target;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Goose_shot_C_Homing) == 0x000008, "Wrong alignment on Goose_shot_C_Homing");
static_assert(sizeof(Goose_shot_C_Homing) == 0x000008, "Wrong size on Goose_shot_C_Homing");
static_assert(offsetof(Goose_shot_C_Homing, Set_target) == 0x000000, "Member 'Goose_shot_C_Homing::Set_target' has a wrong offset!");

}

