#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HardRoute_TrapTrigger_BP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HardRoute_TrapTrigger_BP.HardRoute_TrapTrigger_BP_C
// 0x0050 (0x0270 - 0x0220)
class AHardRoute_TrapTrigger_BP_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Overlap_B;                                         // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FName                                   Tag;                                               // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Sphere_Radius;                                     // 0x0240(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ALTF4_Pawn_SoloPlay_C*              ALTF4_PawnSP;                                      // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_ALTF4_Chick_Pawn_C*                 ALTF4_PawnChick;                                   // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USteamMulti_GameInstance_C*             ALTF4_GI;                                          // 0x0258(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Active_;                                           // 0x0260(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_261[0x3];                                      // 0x0261(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                In_Box_Extent;                                     // 0x0264(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HardRoute_TrapTrigger_BP(int32 EntryPoint);
	void BndEvt__HardRoute_TrapTrigger_BP_Overlap_B_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void BndEvt__HardRoute_TrapTrigger_BP_Overlap_B_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void TrapSignal_Reset();
	void CheckPlayer();
	void ReceiveBeginPlay();
	void TrapOFF_Signal();
	void TrapON_Signal();
	void UserConstructionScript();
	void Trap_On();
	void Trap_Off();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HardRoute_TrapTrigger_BP_C">();
	}
	static class AHardRoute_TrapTrigger_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHardRoute_TrapTrigger_BP_C>();
	}
};
static_assert(alignof(AHardRoute_TrapTrigger_BP_C) == 0x000008, "Wrong alignment on AHardRoute_TrapTrigger_BP_C");
static_assert(sizeof(AHardRoute_TrapTrigger_BP_C) == 0x000270, "Wrong size on AHardRoute_TrapTrigger_BP_C");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, UberGraphFrame) == 0x000220, "Member 'AHardRoute_TrapTrigger_BP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, Overlap_B) == 0x000228, "Member 'AHardRoute_TrapTrigger_BP_C::Overlap_B' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, DefaultSceneRoot) == 0x000230, "Member 'AHardRoute_TrapTrigger_BP_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, Tag) == 0x000238, "Member 'AHardRoute_TrapTrigger_BP_C::Tag' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, Sphere_Radius) == 0x000240, "Member 'AHardRoute_TrapTrigger_BP_C::Sphere_Radius' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, ALTF4_PawnSP) == 0x000248, "Member 'AHardRoute_TrapTrigger_BP_C::ALTF4_PawnSP' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, ALTF4_PawnChick) == 0x000250, "Member 'AHardRoute_TrapTrigger_BP_C::ALTF4_PawnChick' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, ALTF4_GI) == 0x000258, "Member 'AHardRoute_TrapTrigger_BP_C::ALTF4_GI' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, Active_) == 0x000260, "Member 'AHardRoute_TrapTrigger_BP_C::Active_' has a wrong offset!");
static_assert(offsetof(AHardRoute_TrapTrigger_BP_C, In_Box_Extent) == 0x000264, "Member 'AHardRoute_TrapTrigger_BP_C::In_Box_Extent' has a wrong offset!");

}

