#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Item_EpicLeaderboardEntry

#include "Basic.hpp"

#include "Item_EpicLeaderboardEntry_classes.hpp"
#include "Item_EpicLeaderboardEntry_parameters.hpp"


namespace SDK
{

// Function Item_EpicLeaderboardEntry.Item_EpicLeaderboardEntry_C.ExecuteUbergraph_Item_EpicLeaderboardEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItem_EpicLeaderboardEntry_C::ExecuteUbergraph_Item_EpicLeaderboardEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_EpicLeaderboardEntry_C", "ExecuteUbergraph_Item_EpicLeaderboardEntry");

	Params::Item_EpicLeaderboardEntry_C_ExecuteUbergraph_Item_EpicLeaderboardEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Item_EpicLeaderboardEntry.Item_EpicLeaderboardEntry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UItem_EpicLeaderboardEntry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_EpicLeaderboardEntry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Item_EpicLeaderboardEntry.Item_EpicLeaderboardEntry_C.InitFields
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Highlight_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FEpicLeaderboardEntry            ScoreEntry_0                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UItem_EpicLeaderboardEntry_C::InitFields(bool Highlight_0, const struct FEpicLeaderboardEntry& ScoreEntry_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_EpicLeaderboardEntry_C", "InitFields");

	Params::Item_EpicLeaderboardEntry_C_InitFields Parms{};

	Parms.Highlight_0 = Highlight_0;
	Parms.ScoreEntry_0 = std::move(ScoreEntry_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

