#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "InteractableUserWidget_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MainButton.MainButton_C
// 0x0058 (0x0700 - 0x06A8)
class UMainButton_C final : public UInteractableUserWidget_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_MainButton_C;                       // 0x06A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UTextBlock*                             ButtonText;                                        // 0x06B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                MainButton;                                        // 0x06B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                OuterBorder;                                       // 0x06C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x06C8(0x0018)(Edit, BlueprintVisible)
	struct FLinearColor                           MainButtonBgColor;                                 // 0x06E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           MainButtonHighlightColor;                          // 0x06F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MainButton(int32 EntryPoint);
	void OnWidgetEnabled();
	void OnGlobalSettingsApply();
	void PreConstruct(bool IsDesignTime);
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void OnSetHoverEffect(bool bIsHovered, bool bPlaySound);
	void OnPressedRight();
	void OnPressedLeft();
	void BndEvt__MainButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void OnPressedBack();
	void OnPressedSelect();
	void SetHoverEffect(bool bIsHovered);
	void SetupButtonText();
	void SetGlobalSettings();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainButton_C">();
	}
	static class UMainButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMainButton_C>();
	}
};
static_assert(alignof(UMainButton_C) == 0x000008, "Wrong alignment on UMainButton_C");
static_assert(sizeof(UMainButton_C) == 0x000700, "Wrong size on UMainButton_C");
static_assert(offsetof(UMainButton_C, UberGraphFrame_MainButton_C) == 0x0006A8, "Member 'UMainButton_C::UberGraphFrame_MainButton_C' has a wrong offset!");
static_assert(offsetof(UMainButton_C, ButtonText) == 0x0006B0, "Member 'UMainButton_C::ButtonText' has a wrong offset!");
static_assert(offsetof(UMainButton_C, MainButton) == 0x0006B8, "Member 'UMainButton_C::MainButton' has a wrong offset!");
static_assert(offsetof(UMainButton_C, OuterBorder) == 0x0006C0, "Member 'UMainButton_C::OuterBorder' has a wrong offset!");
static_assert(offsetof(UMainButton_C, Text) == 0x0006C8, "Member 'UMainButton_C::Text' has a wrong offset!");
static_assert(offsetof(UMainButton_C, MainButtonBgColor) == 0x0006E0, "Member 'UMainButton_C::MainButtonBgColor' has a wrong offset!");
static_assert(offsetof(UMainButton_C, MainButtonHighlightColor) == 0x0006F0, "Member 'UMainButton_C::MainButtonHighlightColor' has a wrong offset!");

}

