#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainButton

#include "Basic.hpp"

#include "MainButton_classes.hpp"
#include "MainButton_parameters.hpp"


namespace SDK
{

// Function MainButton.MainButton_C.ExecuteUbergraph_MainButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainButton_C::ExecuteUbergraph_MainButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "ExecuteUbergraph_MainButton");

	Params::MainButton_C_ExecuteUbergraph_MainButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainButton.MainButton_C.OnWidgetEnabled
// (BlueprintCallable, BlueprintEvent)

void UMainButton_C::OnWidgetEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "OnWidgetEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.OnGlobalSettingsApply
// (BlueprintCallable, BlueprintEvent)

void UMainButton_C::OnGlobalSettingsApply()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "OnGlobalSettingsApply");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "PreConstruct");

	Params::MainButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainButton.MainButton_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainButton_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.OnSetHoverEffect
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bPlaySound                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainButton_C::OnSetHoverEffect(bool bIsHovered, bool bPlaySound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "OnSetHoverEffect");

	Params::MainButton_C_OnSetHoverEffect Parms{};

	Parms.bIsHovered = bIsHovered;
	Parms.bPlaySound = bPlaySound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainButton.MainButton_C.OnPressedRight
// (BlueprintCallable, BlueprintEvent)

void UMainButton_C::OnPressedRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "OnPressedRight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.OnPressedLeft
// (BlueprintCallable, BlueprintEvent)

void UMainButton_C::OnPressedLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "OnPressedLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.BndEvt__MainButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainButton_C::BndEvt__MainButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "BndEvt__MainButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.OnPressedBack
// (BlueprintCallable, BlueprintEvent)

void UMainButton_C::OnPressedBack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "OnPressedBack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.OnPressedSelect
// (BlueprintCallable, BlueprintEvent)

void UMainButton_C::OnPressedSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "OnPressedSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.SetHoverEffect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainButton_C::SetHoverEffect(bool bIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "SetHoverEffect");

	Params::MainButton_C_SetHoverEffect Parms{};

	Parms.bIsHovered = bIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainButton.MainButton_C.SetupButtonText
// (Public, BlueprintCallable, BlueprintEvent)

void UMainButton_C::SetupButtonText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "SetupButtonText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainButton.MainButton_C.SetGlobalSettings
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UMainButton_C::SetGlobalSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainButton_C", "SetGlobalSettings");

	UObject::ProcessEvent(Func, nullptr);
}

}

