#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapselectMenuWidgetBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InteractableMenuWidgetBP_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MapselectMenuWidgetBP.MapselectMenuWidgetBP_C
// 0x0070 (0x06B0 - 0x0640)
class UMapselectMenuWidgetBP_C final : public UInteractableMenuWidgetBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_MapselectMenuWidgetBP_C;            // 0x0640(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UZero1_MapSelectButton_C*               Zero1_MapSelectButton;                             // 0x0648(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCenterButton_C*                        Zero2_RecordButton;                                // 0x0650(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNavigationKeyButton_C*                 BackButton;                                        // 0x0658(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDecisionDialogWidgetBP_C*              DecisionDialogWidgetBP;                            // 0x0660(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULoadingScreenWidgetBP_C*               LoadingScreenWidgetBP;                             // 0x0668(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                MapSelectBorder;                                   // 0x0670(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           MapSelectPanel;                                    // 0x0678(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           MenuCanvasPanel;                                   // 0x0680(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             MenuTitleText;                                     // 0x0688(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnClickedBack;                                     // 0x0690(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UMainMenuContainerWidgetBP_C*           MainMenuWidget;                                    // 0x06A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USteamMulti_GameInstance_C*             ALTF4_GI;                                          // 0x06A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void OnClickedBack__DelegateSignature();
	void ExecuteUbergraph_MapselectMenuWidgetBP(int32 EntryPoint);
	void BndEvt__MapSelect_WidgetBP_02_RecordButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void BndEvt__MapSelect_WidgetBP_01_CastleMapSelectButton_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature();
	void OnGlobalSettingsApply();
	void BndEvt__BackButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void SetGlobalSettings();
	void ShowLoadingScreen(bool bIsVisible);
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void OnNavigationExit(class UInteractableMenuWidgetBP_C* NavigateToMenu, class UInteractableMenuWidgetBP_C* NavigateFromMenu);
	void OnNavigationEnter(class UInteractableMenuWidgetBP_C* NavigateFromMenu, bool bIsGamepadBeingUsed_0);
	void OnPressedBack();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MapselectMenuWidgetBP_C">();
	}
	static class UMapselectMenuWidgetBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMapselectMenuWidgetBP_C>();
	}
};
static_assert(alignof(UMapselectMenuWidgetBP_C) == 0x000008, "Wrong alignment on UMapselectMenuWidgetBP_C");
static_assert(sizeof(UMapselectMenuWidgetBP_C) == 0x0006B0, "Wrong size on UMapselectMenuWidgetBP_C");
static_assert(offsetof(UMapselectMenuWidgetBP_C, UberGraphFrame_MapselectMenuWidgetBP_C) == 0x000640, "Member 'UMapselectMenuWidgetBP_C::UberGraphFrame_MapselectMenuWidgetBP_C' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, Zero1_MapSelectButton) == 0x000648, "Member 'UMapselectMenuWidgetBP_C::Zero1_MapSelectButton' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, Zero2_RecordButton) == 0x000650, "Member 'UMapselectMenuWidgetBP_C::Zero2_RecordButton' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, BackButton) == 0x000658, "Member 'UMapselectMenuWidgetBP_C::BackButton' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, DecisionDialogWidgetBP) == 0x000660, "Member 'UMapselectMenuWidgetBP_C::DecisionDialogWidgetBP' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, LoadingScreenWidgetBP) == 0x000668, "Member 'UMapselectMenuWidgetBP_C::LoadingScreenWidgetBP' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, MapSelectBorder) == 0x000670, "Member 'UMapselectMenuWidgetBP_C::MapSelectBorder' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, MapSelectPanel) == 0x000678, "Member 'UMapselectMenuWidgetBP_C::MapSelectPanel' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, MenuCanvasPanel) == 0x000680, "Member 'UMapselectMenuWidgetBP_C::MenuCanvasPanel' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, MenuTitleText) == 0x000688, "Member 'UMapselectMenuWidgetBP_C::MenuTitleText' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, OnClickedBack) == 0x000690, "Member 'UMapselectMenuWidgetBP_C::OnClickedBack' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, MainMenuWidget) == 0x0006A0, "Member 'UMapselectMenuWidgetBP_C::MainMenuWidget' has a wrong offset!");
static_assert(offsetof(UMapselectMenuWidgetBP_C, ALTF4_GI) == 0x0006A8, "Member 'UMapselectMenuWidgetBP_C::ALTF4_GI' has a wrong offset!");

}

