#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OptionsPicker_IngameVer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "InteractableUserWidget_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass OptionsPicker_IngameVer.OptionsPicker_IngameVer_C
// 0x0100 (0x07A8 - 0x06A8)
class UOptionsPicker_IngameVer_C final : public UInteractableUserWidget_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_OptionsPicker_IngameVer_C;          // 0x06A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UButton*                                HoverButton;                                       // 0x06B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                LeftBorder;                                        // 0x06B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                NextOptionButton;                                  // 0x06C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 NextOptionButtonImage;                             // 0x06C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             OptionNameText;                                    // 0x06D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         OptionsHorizontalBox;                              // 0x06D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                OuterBorder;                                       // 0x06E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             PickedOptionText;                                  // 0x06E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                PreviousOptionButton;                              // 0x06F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PreviousOptionButtonImage;                         // 0x06F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                RightBorder;                                       // 0x0700(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             SubButtonsScrollBox;                               // 0x0708(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class FText>                           OptionsArray;                                      // 0x0710(0x0010)(Edit, BlueprintVisible)
	int32                                         ActiveOptionIndex;                                 // 0x0720(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_724[0x4];                                      // 0x0724(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UOptionsPickerSubButton_C*>      SubButtonWidgets;                                  // 0x0728(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	FMulticastInlineDelegateProperty_             OnOptionChanged;                                   // 0x0738(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         DefaultOptionIndex;                                // 0x0748(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74C[0x4];                                      // 0x074C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UTexture2D*>                     OptionsImageArray;                                 // 0x0750(0x0010)(Edit, BlueprintVisible)
	bool                                          ShowSubButtons;                                    // 0x0760(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_761[0x3];                                      // 0x0761(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           OptionsPickerBgColor;                              // 0x0764(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           OptionsPickerHighlightColor;                       // 0x0774(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           OptionsPickerExtraHighlightColor;                  // 0x0784(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           OptionsPickerOptionButtonBgColor;                  // 0x0794(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnOptionChanged__DelegateSignature(int32 ActiveIndex);
	void ExecuteUbergraph_OptionsPicker_IngameVer(int32 EntryPoint);
	void BndEvt__PreviousOptionButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__NextOptionButton_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__NextOptionButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__PreviousOptionButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void OnGlobalSettingsApply();
	void OnSetHoverEffect(bool bIsHovered, bool bPlaySound);
	void OnPressedRight();
	void OnPressedLeft();
	void BndEvt__HoverButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void Setup();
	void SubOnClick(int32 InIndex);
	void BndEvt__PreviousOptionButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__NextOptionButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void PreConstruct(bool IsDesignTime);
	void SetActiveOption(int32 InIndex, bool bOptionChangedIgnore, bool bPlaySound);
	void UpdateSubButtons();
	void SetHoverEffect(bool IsOn);
	void SetCurrentIndex(int32 InIndex, bool bPlaySound);
	void SetChangeOptionsButtonVisibility(bool bIsVisible);
	void SetupOptionNameText();
	void SetGlobalSettings();
	void SetPickedOptionTextSettings();
	void SetCurrentImage(int32 Index_0);
	void SetChangeOptionButtonHoverEffect(bool bIsHovered, class UImage* InImage);
	void SetDefaultOptionIndex();
	void IsInOptionsArrayBounds(int32 InIndex, bool* bIsInBounds);
	void SetPickedOptionText();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"OptionsPicker_IngameVer_C">();
	}
	static class UOptionsPicker_IngameVer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOptionsPicker_IngameVer_C>();
	}
};
static_assert(alignof(UOptionsPicker_IngameVer_C) == 0x000008, "Wrong alignment on UOptionsPicker_IngameVer_C");
static_assert(sizeof(UOptionsPicker_IngameVer_C) == 0x0007A8, "Wrong size on UOptionsPicker_IngameVer_C");
static_assert(offsetof(UOptionsPicker_IngameVer_C, UberGraphFrame_OptionsPicker_IngameVer_C) == 0x0006A8, "Member 'UOptionsPicker_IngameVer_C::UberGraphFrame_OptionsPicker_IngameVer_C' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, HoverButton) == 0x0006B0, "Member 'UOptionsPicker_IngameVer_C::HoverButton' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, LeftBorder) == 0x0006B8, "Member 'UOptionsPicker_IngameVer_C::LeftBorder' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, NextOptionButton) == 0x0006C0, "Member 'UOptionsPicker_IngameVer_C::NextOptionButton' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, NextOptionButtonImage) == 0x0006C8, "Member 'UOptionsPicker_IngameVer_C::NextOptionButtonImage' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionNameText) == 0x0006D0, "Member 'UOptionsPicker_IngameVer_C::OptionNameText' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionsHorizontalBox) == 0x0006D8, "Member 'UOptionsPicker_IngameVer_C::OptionsHorizontalBox' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OuterBorder) == 0x0006E0, "Member 'UOptionsPicker_IngameVer_C::OuterBorder' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, PickedOptionText) == 0x0006E8, "Member 'UOptionsPicker_IngameVer_C::PickedOptionText' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, PreviousOptionButton) == 0x0006F0, "Member 'UOptionsPicker_IngameVer_C::PreviousOptionButton' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, PreviousOptionButtonImage) == 0x0006F8, "Member 'UOptionsPicker_IngameVer_C::PreviousOptionButtonImage' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, RightBorder) == 0x000700, "Member 'UOptionsPicker_IngameVer_C::RightBorder' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, SubButtonsScrollBox) == 0x000708, "Member 'UOptionsPicker_IngameVer_C::SubButtonsScrollBox' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionsArray) == 0x000710, "Member 'UOptionsPicker_IngameVer_C::OptionsArray' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, ActiveOptionIndex) == 0x000720, "Member 'UOptionsPicker_IngameVer_C::ActiveOptionIndex' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, SubButtonWidgets) == 0x000728, "Member 'UOptionsPicker_IngameVer_C::SubButtonWidgets' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OnOptionChanged) == 0x000738, "Member 'UOptionsPicker_IngameVer_C::OnOptionChanged' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, DefaultOptionIndex) == 0x000748, "Member 'UOptionsPicker_IngameVer_C::DefaultOptionIndex' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionsImageArray) == 0x000750, "Member 'UOptionsPicker_IngameVer_C::OptionsImageArray' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, ShowSubButtons) == 0x000760, "Member 'UOptionsPicker_IngameVer_C::ShowSubButtons' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionsPickerBgColor) == 0x000764, "Member 'UOptionsPicker_IngameVer_C::OptionsPickerBgColor' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionsPickerHighlightColor) == 0x000774, "Member 'UOptionsPicker_IngameVer_C::OptionsPickerHighlightColor' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionsPickerExtraHighlightColor) == 0x000784, "Member 'UOptionsPicker_IngameVer_C::OptionsPickerExtraHighlightColor' has a wrong offset!");
static_assert(offsetof(UOptionsPicker_IngameVer_C, OptionsPickerOptionButtonBgColor) == 0x000794, "Member 'UOptionsPicker_IngameVer_C::OptionsPickerOptionButtonBgColor' has a wrong offset!");

}

