#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RotationWoodenBoard_BP

#include "Basic.hpp"

#include "RotationWoodenBoard_BP_classes.hpp"
#include "RotationWoodenBoard_BP_parameters.hpp"


namespace SDK
{

// Function RotationWoodenBoard_BP.RotationWoodenBoard_BP_C.ExecuteUbergraph_RotationWoodenBoard_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ARotationWoodenBoard_BP_C::ExecuteUbergraph_RotationWoodenBoard_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RotationWoodenBoard_BP_C", "ExecuteUbergraph_RotationWoodenBoard_BP");

	Params::RotationWoodenBoard_BP_C_ExecuteUbergraph_RotationWoodenBoard_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RotationWoodenBoard_BP.RotationWoodenBoard_BP_C.Stop
// (BlueprintCallable, BlueprintEvent)

void ARotationWoodenBoard_BP_C::Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RotationWoodenBoard_BP_C", "Stop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RotationWoodenBoard_BP.RotationWoodenBoard_BP_C.Active
// (BlueprintCallable, BlueprintEvent)

void ARotationWoodenBoard_BP_C::Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RotationWoodenBoard_BP_C", "Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RotationWoodenBoard_BP.RotationWoodenBoard_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ARotationWoodenBoard_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RotationWoodenBoard_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

