#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SavePointSpawn_BP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function SavePointSpawn_BP.SavePointSpawn_BP_C.ExecuteUbergraph_SavePointSpawn_BP
// 0x0080 (0x0080 - 0x0000)
struct SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0010(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakVector_X;                            // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38[0x8];                                       // 0x0038(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0040(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASave_Point_C*                          CallFunc_FinishSpawningActor_ReturnValue;          // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP) == 0x000010, "Wrong alignment on SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP");
static_assert(sizeof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP) == 0x000080, "Wrong size on SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, EntryPoint) == 0x000000, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000004, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_MakeRotator_ReturnValue) == 0x000010, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_BreakVector_X) == 0x00001C, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_BreakVector_Y) == 0x000020, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_BreakVector_Z) == 0x000024, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_Add_FloatFloat_ReturnValue) == 0x000028, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_MakeVector_ReturnValue) == 0x00002C, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_MakeTransform_ReturnValue) == 0x000040, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000070, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP, CallFunc_FinishSpawningActor_ReturnValue) == 0x000078, "Member 'SavePointSpawn_BP_C_ExecuteUbergraph_SavePointSpawn_BP::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");

}

