#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Save_Point

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Save_Point.Save_Point_C.ExecuteUbergraph_Save_Point
// 0x04E0 (0x04E0 - 0x0000)
struct Save_Point_C_ExecuteUbergraph_Save_Point final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Gameinstance_C>   K2Node_DynamicCast_AsBPI_Gameinstance;             // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USteamMulti_GameInstance_C*             CallFunc_ALTF4GameInstanceRef_ALTF4_GI;            // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_WrittenAchievementName_1;       // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_WrittenProgress_1;              // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_WrittenUserTag_1;               // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_WrittenAchievementName;         // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_WrittenProgress;                // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_WrittenUserTag;                 // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> K2Node_CreateDelegate_OutputDelegate;              // 0x0060(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         ___int_Variable;                                   // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ___float_Variable;                                 // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   ___name_Variable;                                  // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_IsClosed_Variable;                         // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          ___bool_Has_Been_Initd_Variable;                   // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ___bool_Has_Been_Initd_Variable_1;                 // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9A[0x2];                                       // 0x009A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x00A0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x00AC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_HitComponent;           // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_3;           // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_3;            // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_NormalImpulse;          // 0x00E0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_ComponentBoundEvent_Hit;                    // 0x00EC(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AGooseShot_Replicate_BP_C*              K2Node_DynamicCast_AsGoose_Shot_Replicate_BP;      // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGooseShot_BP_C*                        K2Node_DynamicCast_AsGoose_Shot_BP;                // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x7];                                      // 0x0191(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_2;  // 0x0198(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_2;           // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_2;            // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_2;       // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep_2;           // 0x01B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B5[0x3];                                      // 0x01B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult_2;          // 0x01B8(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ALTF4_Pawn_C*                       K2Node_DynamicCast_AsBP_ALTF4_Pawn;                // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x0258(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0268(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x0270(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep_1;           // 0x0274(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_275[0x3];                                      // 0x0275(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult_1;          // 0x0278(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0308(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0310(0x0010)(ZeroConstructor, NoDestructor)
	class UAchievementQueryCallbackProxy*         CallFunc_CacheAchievements_ReturnValue;            // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAchievementWriteCallbackProxy*         CallFunc_WriteAchievementProgress_ReturnValue;     // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0330(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0331(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_332[0x6];                                      // 0x0332(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_1;            // 0x0338(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Gameinstance_C>   K2Node_DynamicCast_AsBPI_Gameinstance_1;           // 0x0340(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_351[0x7];                                      // 0x0351(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0358(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0368(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0370(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x0374(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_375[0x3];                                      // 0x0375(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0378(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_404[0x4];                                      // 0x0404(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USteamMulti_GameInstance_C*             CallFunc_ALTF4GameInstanceRef_ALTF4_GI_1;          // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AEgg_shot_BP_C*                         K2Node_DynamicCast_AsEgg_Shot_BP;                  // 0x0410(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0418(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0419(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41A[0x2];                                      // 0x041A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x041C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGooseShot_Replicate_BP_C*              K2Node_DynamicCast_AsGoose_Shot_Replicate_BP_1;    // 0x0420(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0428(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_429[0x7];                                      // 0x0429(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGooseShot_BP_C*                        K2Node_DynamicCast_AsGoose_Shot_BP_1;              // 0x0430(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0438(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ___bool_IsClosed_Variable_1;                       // 0x0439(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_43A[0x2];                                      // 0x043A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x043C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0448(0x0010)(ZeroConstructor, NoDestructor)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0458(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_2;    // 0x0460(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x046C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_3;    // 0x0478(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_484[0x4];                                      // 0x0484(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue_1;     // 0x0488(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_2;            // 0x0490(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USteamMulti_GameInstance_C*             K2Node_DynamicCast_AsSteam_Multi_Game_Instance;    // 0x0498(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x04A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A1[0x3];                                      // 0x04A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_4;    // 0x04A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue_2;     // 0x04B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x04B8(0x0010)(ZeroConstructor, NoDestructor)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_5;    // 0x04C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_2;           // 0x04D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Save_Point_C_ExecuteUbergraph_Save_Point) == 0x000008, "Wrong alignment on Save_Point_C_ExecuteUbergraph_Save_Point");
static_assert(sizeof(Save_Point_C_ExecuteUbergraph_Save_Point) == 0x0004E0, "Wrong size on Save_Point_C_ExecuteUbergraph_Save_Point");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, EntryPoint) == 0x000000, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::EntryPoint' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_GetGameInstance_ReturnValue) == 0x000008, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsBPI_Gameinstance) == 0x000010, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsBPI_Gameinstance' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_ALTF4GameInstanceRef_ALTF4_GI) == 0x000028, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_ALTF4GameInstanceRef_ALTF4_GI' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_Conv_IntToString_ReturnValue) == 0x000030, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CustomEvent_WrittenAchievementName_1) == 0x000040, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CustomEvent_WrittenAchievementName_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CustomEvent_WrittenProgress_1) == 0x000048, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CustomEvent_WrittenProgress_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CustomEvent_WrittenUserTag_1) == 0x00004C, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CustomEvent_WrittenUserTag_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CustomEvent_WrittenAchievementName) == 0x000050, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CustomEvent_WrittenAchievementName' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CustomEvent_WrittenProgress) == 0x000058, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CustomEvent_WrittenProgress' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CustomEvent_WrittenUserTag) == 0x00005C, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CustomEvent_WrittenUserTag' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CreateDelegate_OutputDelegate) == 0x000060, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, ___int_Variable) == 0x000070, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::___int_Variable' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, ___float_Variable) == 0x000074, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::___float_Variable' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, ___name_Variable) == 0x000078, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::___name_Variable' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, ___bool_IsClosed_Variable) == 0x000080, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::___bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_Conv_NameToString_ReturnValue) == 0x000088, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, ___bool_Has_Been_Initd_Variable) == 0x000098, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::___bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, ___bool_Has_Been_Initd_Variable_1) == 0x000099, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::___bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_Event_DeltaSeconds) == 0x00009C, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0000A0, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x0000AC, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_Add_VectorVector_ReturnValue) == 0x0000B8, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_HitComponent) == 0x0000C8, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_HitComponent' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherActor_3) == 0x0000D0, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherActor_3' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherComp_3) == 0x0000D8, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherComp_3' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_NormalImpulse) == 0x0000E0, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_NormalImpulse' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_Hit) == 0x0000EC, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_Hit' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsGoose_Shot_Replicate_BP) == 0x000178, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsGoose_Shot_Replicate_BP' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_1) == 0x000180, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsGoose_Shot_BP) == 0x000188, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsGoose_Shot_BP' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_2) == 0x000190, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OverlappedComponent_2) == 0x000198, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OverlappedComponent_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherActor_2) == 0x0001A0, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherActor_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherComp_2) == 0x0001A8, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherComp_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherBodyIndex_2) == 0x0001B0, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherBodyIndex_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_bFromSweep_2) == 0x0001B4, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_bFromSweep_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_SweepResult_2) == 0x0001B8, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_SweepResult_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsBP_ALTF4_Pawn) == 0x000248, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsBP_ALTF4_Pawn' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_3) == 0x000250, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x000258, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000260, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000268, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x000270, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_bFromSweep_1) == 0x000274, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_bFromSweep_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_SweepResult_1) == 0x000278, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_SweepResult_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_GetPlayerController_ReturnValue) == 0x000308, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CreateDelegate_OutputDelegate_1) == 0x000310, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_CacheAchievements_ReturnValue) == 0x000320, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_CacheAchievements_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_WriteAchievementProgress_ReturnValue) == 0x000328, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_WriteAchievementProgress_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_IsValid_ReturnValue) == 0x000330, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_IsValid_ReturnValue_1) == 0x000331, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_GetGameInstance_ReturnValue_1) == 0x000338, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_GetGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsBPI_Gameinstance_1) == 0x000340, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsBPI_Gameinstance_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_4) == 0x000350, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000358, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherActor) == 0x000360, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherComp) == 0x000368, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000370, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_bFromSweep) == 0x000374, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_ComponentBoundEvent_SweepResult) == 0x000378, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_ALTF4GameInstanceRef_ALTF4_GI_1) == 0x000408, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_ALTF4GameInstanceRef_ALTF4_GI_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsEgg_Shot_BP) == 0x000410, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsEgg_Shot_BP' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_5) == 0x000418, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000419, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_Add_IntInt_ReturnValue) == 0x00041C, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsGoose_Shot_Replicate_BP_1) == 0x000420, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsGoose_Shot_Replicate_BP_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_6) == 0x000428, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsGoose_Shot_BP_1) == 0x000430, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsGoose_Shot_BP_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_7) == 0x000438, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, ___bool_IsClosed_Variable_1) == 0x000439, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::___bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x00043C, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CreateDelegate_OutputDelegate_2) == 0x000448, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000458, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_K2_GetComponentLocation_ReturnValue_2) == 0x000460, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_K2_GetComponentLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_Add_VectorVector_ReturnValue_1) == 0x00046C, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_K2_GetComponentLocation_ReturnValue_3) == 0x000478, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_K2_GetComponentLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_SpawnEmitterAtLocation_ReturnValue_1) == 0x000488, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_SpawnEmitterAtLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_GetGameInstance_ReturnValue_2) == 0x000490, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_GetGameInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_AsSteam_Multi_Game_Instance) == 0x000498, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_AsSteam_Multi_Game_Instance' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_DynamicCast_bSuccess_8) == 0x0004A0, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_K2_GetComponentLocation_ReturnValue_4) == 0x0004A4, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_K2_GetComponentLocation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_SpawnEmitterAtLocation_ReturnValue_2) == 0x0004B0, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_SpawnEmitterAtLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, K2Node_CreateDelegate_OutputDelegate_3) == 0x0004B8, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_K2_GetComponentLocation_ReturnValue_5) == 0x0004C8, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_K2_GetComponentLocation_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Save_Point_C_ExecuteUbergraph_Save_Point, CallFunc_Add_VectorVector_ReturnValue_2) == 0x0004D4, "Member 'Save_Point_C_ExecuteUbergraph_Save_Point::CallFunc_Add_VectorVector_ReturnValue_2' has a wrong offset!");

// Function Save_Point.Save_Point_C.BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000B0, "Wrong size on Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Save_Point_C_BndEvt__BallonHitCollison_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function Save_Point.Save_Point_C.BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000B0, "Wrong size on Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Save_Point_C_BndEvt__SavePointDeleteCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function Save_Point.Save_Point_C.BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000B0, "Wrong size on Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'Save_Point_C_BndEvt__Save_Box_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function Save_Point.Save_Point_C.BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0024(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature) == 0x000008, "Wrong alignment on Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature");
static_assert(sizeof(Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature) == 0x0000B0, "Wrong size on Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature");
static_assert(offsetof(Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, HitComponent) == 0x000000, "Member 'Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::HitComponent' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, NormalImpulse) == 0x000018, "Member 'Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::NormalImpulse' has a wrong offset!");
static_assert(offsetof(Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature, Hit) == 0x000024, "Member 'Save_Point_C_BndEvt__Balloon_K2Node_ComponentBoundEvent_4_ComponentHitSignature__DelegateSignature::Hit' has a wrong offset!");

// Function Save_Point.Save_Point_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Save_Point_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Save_Point_C_ReceiveTick) == 0x000004, "Wrong alignment on Save_Point_C_ReceiveTick");
static_assert(sizeof(Save_Point_C_ReceiveTick) == 0x000004, "Wrong size on Save_Point_C_ReceiveTick");
static_assert(offsetof(Save_Point_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'Save_Point_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function Save_Point.Save_Point_C.OnSuccess_3774068A4FAD579103AF2D86CB50B5FA
// 0x0010 (0x0010 - 0x0000)
struct Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA final
{
public:
	class FName                                   WrittenAchievementName;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WrittenProgress;                                   // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WrittenUserTag;                                    // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA) == 0x000004, "Wrong alignment on Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA");
static_assert(sizeof(Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA) == 0x000010, "Wrong size on Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA");
static_assert(offsetof(Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA, WrittenAchievementName) == 0x000000, "Member 'Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA::WrittenAchievementName' has a wrong offset!");
static_assert(offsetof(Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA, WrittenProgress) == 0x000008, "Member 'Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA::WrittenProgress' has a wrong offset!");
static_assert(offsetof(Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA, WrittenUserTag) == 0x00000C, "Member 'Save_Point_C_OnSuccess_3774068A4FAD579103AF2D86CB50B5FA::WrittenUserTag' has a wrong offset!");

// Function Save_Point.Save_Point_C.OnFailure_3774068A4FAD579103AF2D86CB50B5FA
// 0x0010 (0x0010 - 0x0000)
struct Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA final
{
public:
	class FName                                   WrittenAchievementName;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WrittenProgress;                                   // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WrittenUserTag;                                    // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA) == 0x000004, "Wrong alignment on Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA");
static_assert(sizeof(Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA) == 0x000010, "Wrong size on Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA");
static_assert(offsetof(Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA, WrittenAchievementName) == 0x000000, "Member 'Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA::WrittenAchievementName' has a wrong offset!");
static_assert(offsetof(Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA, WrittenProgress) == 0x000008, "Member 'Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA::WrittenProgress' has a wrong offset!");
static_assert(offsetof(Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA, WrittenUserTag) == 0x00000C, "Member 'Save_Point_C_OnFailure_3774068A4FAD579103AF2D86CB50B5FA::WrittenUserTag' has a wrong offset!");

// Function Save_Point.Save_Point_C.UserConstructionScript
// 0x008C (0x008C - 0x0000)
struct Save_Point_C_UserConstructionScript final
{
public:
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0000(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Save_Point_C_UserConstructionScript) == 0x000004, "Wrong alignment on Save_Point_C_UserConstructionScript");
static_assert(sizeof(Save_Point_C_UserConstructionScript) == 0x00008C, "Wrong size on Save_Point_C_UserConstructionScript");
static_assert(offsetof(Save_Point_C_UserConstructionScript, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000000, "Member 'Save_Point_C_UserConstructionScript::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");

}

