#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShortCutRouteWall_BP

#include "Basic.hpp"

#include "ShortCutRouteWall_BP_classes.hpp"
#include "ShortCutRouteWall_BP_parameters.hpp"


namespace SDK
{

// Function ShortCutRouteWall_BP.ShortCutRouteWall_BP_C.ExecuteUbergraph_ShortCutRouteWall_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AShortCutRouteWall_BP_C::ExecuteUbergraph_ShortCutRouteWall_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShortCutRouteWall_BP_C", "ExecuteUbergraph_ShortCutRouteWall_BP");

	Params::ShortCutRouteWall_BP_C_ExecuteUbergraph_ShortCutRouteWall_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShortCutRouteWall_BP.ShortCutRouteWall_BP_C.Rollback
// (BlueprintCallable, BlueprintEvent)

void AShortCutRouteWall_BP_C::Rollback()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShortCutRouteWall_BP_C", "Rollback");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShortCutRouteWall_BP.ShortCutRouteWall_BP_C.Active
// (BlueprintCallable, BlueprintEvent)

void AShortCutRouteWall_BP_C::Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShortCutRouteWall_BP_C", "Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShortCutRouteWall_BP.ShortCutRouteWall_BP_C.Rota__UpdateFunc
// (BlueprintEvent)

void AShortCutRouteWall_BP_C::Rota__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShortCutRouteWall_BP_C", "Rota__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShortCutRouteWall_BP.ShortCutRouteWall_BP_C.Rota__FinishedFunc
// (BlueprintEvent)

void AShortCutRouteWall_BP_C::Rota__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShortCutRouteWall_BP_C", "Rota__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

