#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StageA01_FishSpwan_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function StageA01_FishSpwan_BP.StageA01_FishSpwan_BP_C.ExecuteUbergraph_StageA01_FishSpwan_BP
// 0x0100 (0x0100 - 0x0000)
struct StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0020(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x005C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0068(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0088(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue_2;         // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x00A0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x00B0(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AStageA01_FishShot_BP_C*                CallFunc_FinishSpawningActor_ReturnValue;          // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue_3;         // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x00F8(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP) == 0x000010, "Wrong alignment on StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP");
static_assert(sizeof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP) == 0x000100, "Wrong size on StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, EntryPoint) == 0x000000, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000018, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000020, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_BreakTransform_Location) == 0x000050, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_BreakTransform_Rotation) == 0x00005C, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_BreakTransform_Scale) == 0x000068, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_BreakRotator_Roll) == 0x000074, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_BreakRotator_Pitch) == 0x000078, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_BreakRotator_Yaw) == 0x00007C, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_RandomFloatInRange_ReturnValue) == 0x000080, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x000084, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000088, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000094, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_RandomFloatInRange_ReturnValue_2) == 0x000098, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_RandomFloatInRange_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x00009C, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_MakeRotator_ReturnValue) == 0x0000A0, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_MakeTransform_ReturnValue) == 0x0000B0, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0000E0, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_FinishSpawningActor_ReturnValue) == 0x0000E8, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_RandomFloatInRange_ReturnValue_3) == 0x0000F0, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_RandomFloatInRange_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x0000F8, "Member 'StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");

}

