#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StageA01_FishSpwan_BP

#include "Basic.hpp"

#include "StageA01_FishSpwan_BP_classes.hpp"
#include "StageA01_FishSpwan_BP_parameters.hpp"


namespace SDK
{

// Function StageA01_FishSpwan_BP.StageA01_FishSpwan_BP_C.fire_dispatcher__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void AStageA01_FishSpwan_BP_C::Fire_dispatcher__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StageA01_FishSpwan_BP_C", "fire_dispatcher__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StageA01_FishSpwan_BP.StageA01_FishSpwan_BP_C.ExecuteUbergraph_StageA01_FishSpwan_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AStageA01_FishSpwan_BP_C::ExecuteUbergraph_StageA01_FishSpwan_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StageA01_FishSpwan_BP_C", "ExecuteUbergraph_StageA01_FishSpwan_BP");

	Params::StageA01_FishSpwan_BP_C_ExecuteUbergraph_StageA01_FishSpwan_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StageA01_FishSpwan_BP.StageA01_FishSpwan_BP_C.FIRE_LOOP_FISH
// (BlueprintCallable, BlueprintEvent)

void AStageA01_FishSpwan_BP_C::FIRE_LOOP_FISH()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StageA01_FishSpwan_BP_C", "FIRE_LOOP_FISH");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StageA01_FishSpwan_BP.StageA01_FishSpwan_BP_C.stop_fire
// (BlueprintCallable, BlueprintEvent)

void AStageA01_FishSpwan_BP_C::Stop_fire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StageA01_FishSpwan_BP_C", "stop_fire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StageA01_FishSpwan_BP.StageA01_FishSpwan_BP_C.Fire
// (BlueprintCallable, BlueprintEvent)

void AStageA01_FishSpwan_BP_C::Fire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StageA01_FishSpwan_BP_C", "Fire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StageA01_FishSpwan_BP.StageA01_FishSpwan_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AStageA01_FishSpwan_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StageA01_FishSpwan_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

