#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UpdownFootRest_02_BP

#include "Basic.hpp"

#include "UpdownFootRest_02_BP_classes.hpp"
#include "UpdownFootRest_02_BP_parameters.hpp"


namespace SDK
{

// Function UpdownFootRest_02_BP.UpdownFootRest_02_BP_C.ExecuteUbergraph_UpdownFootRest_02_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUpdownFootRest_02_BP_C::ExecuteUbergraph_UpdownFootRest_02_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpdownFootRest_02_BP_C", "ExecuteUbergraph_UpdownFootRest_02_BP");

	Params::UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UpdownFootRest_02_BP.UpdownFootRest_02_BP_C.StopMove
// (BlueprintCallable, BlueprintEvent)

void AUpdownFootRest_02_BP_C::StopMove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpdownFootRest_02_BP_C", "StopMove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpdownFootRest_02_BP.UpdownFootRest_02_BP_C.Active
// (BlueprintCallable, BlueprintEvent)

void AUpdownFootRest_02_BP_C::Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpdownFootRest_02_BP_C", "Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpdownFootRest_02_BP.UpdownFootRest_02_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AUpdownFootRest_02_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpdownFootRest_02_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpdownFootRest_02_BP.UpdownFootRest_02_BP_C.Move__UpdateFunc
// (BlueprintEvent)

void AUpdownFootRest_02_BP_C::Move__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpdownFootRest_02_BP_C", "Move__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpdownFootRest_02_BP.UpdownFootRest_02_BP_C.Move__FinishedFunc
// (BlueprintEvent)

void AUpdownFootRest_02_BP_C::Move__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpdownFootRest_02_BP_C", "Move__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

