#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UpdownFootRest_02_BP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function UpdownFootRest_02_BP.UpdownFootRest_02_BP_C.ExecuteUbergraph_UpdownFootRest_02_BP
// 0x009C (0x009C - 0x0000)
struct UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue;                        // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0010(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP) == 0x000004, "Wrong alignment on UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP");
static_assert(sizeof(UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP) == 0x00009C, "Wrong size on UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP");
static_assert(offsetof(UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP, EntryPoint) == 0x000000, "Member 'UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP, CallFunc_VLerp_ReturnValue) == 0x000004, "Member 'UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP::CallFunc_VLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000010, "Member 'UpdownFootRest_02_BP_C_ExecuteUbergraph_UpdownFootRest_02_BP::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");

}

