#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UpDownBalde_Trap_BP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function UpDownBalde_Trap_BP.UpDownBalde_Trap_BP_C.ExecuteUbergraph_UpDownBalde_Trap_BP
// 0x0160 (0x0160 - 0x0000)
struct UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_Has_Been_Initd_Variable;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ___bool_IsClosed_Variable;                         // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_HitComponent;           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_NormalImpulse;          // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_ComponentBoundEvent_Hit;                    // 0x002C(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class ABP_ALTF4_Pawn_SoloPlay_C*              K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play;      // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x3];                                       // 0x00C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_VLerp_ReturnValue;                        // 0x00C4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x00D0(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP) == 0x000008, "Wrong alignment on UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP");
static_assert(sizeof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP) == 0x000160, "Wrong size on UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, EntryPoint) == 0x000000, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, ___bool_Has_Been_Initd_Variable) == 0x000004, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::___bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, ___bool_IsClosed_Variable) == 0x000005, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::___bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, K2Node_ComponentBoundEvent_HitComponent) == 0x000008, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::K2Node_ComponentBoundEvent_HitComponent' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, K2Node_ComponentBoundEvent_OtherActor) == 0x000010, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, K2Node_ComponentBoundEvent_OtherComp) == 0x000018, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, K2Node_ComponentBoundEvent_NormalImpulse) == 0x000020, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::K2Node_ComponentBoundEvent_NormalImpulse' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, K2Node_ComponentBoundEvent_Hit) == 0x00002C, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::K2Node_ComponentBoundEvent_Hit' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play) == 0x0000B8, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::K2Node_DynamicCast_AsBP_ALTF4_Pawn_Solo_Play' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, K2Node_DynamicCast_bSuccess) == 0x0000C0, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, CallFunc_VLerp_ReturnValue) == 0x0000C4, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::CallFunc_VLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x0000D0, "Member 'UpDownBalde_Trap_BP_C_ExecuteUbergraph_UpDownBalde_Trap_BP::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");

// Function UpDownBalde_Trap_BP.UpDownBalde_Trap_BP_C.BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0024(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x000008, "Wrong alignment on UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(sizeof(UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x0000B0, "Wrong size on UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(offsetof(UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, HitComponent) == 0x000000, "Member 'UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::HitComponent' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, NormalImpulse) == 0x000018, "Member 'UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::NormalImpulse' has a wrong offset!");
static_assert(offsetof(UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, Hit) == 0x000024, "Member 'UpDownBalde_Trap_BP_C_BndEvt__UpDownBalde_Trap_BP_SM_Axe_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::Hit' has a wrong offset!");

}

